schema:
  - ${API_ENDPOINT:"http://localhost:4000/graphql"}:
      headers:
        Authorization: ${API_PUBLIC_KEY:""}
documents: ./src/**/*.{graphql,gql,ts,tsx}

extensions:
  codegen:
    generates:
      ./src/generated/graphql.tsx:
        plugins:
          - typescript
          - typescript-operations
